### PR TITLE
Setting lcov to verision 1.16

### PR DESCRIPTION
**Pull request by roconnor-blockstream**
The withCoverage option doesn't work at the moment with lcov-2.1.

### CODE REVIEW

**Comment by roconnor-blockstream** [comment]
https://github.com/bitcoin/bitcoin/issues/28468 discusses some workarounds bitcoin core had to do.  However it seems after moving to CMake, they might just be using the llvm native tooling for coverage instead.

For now, the easiest thing is to revert back to the previous version of lcov.

**Comment by roconnor-blockstream** [comment]
@apoelstra, would you like to try to build this with `nix-build ~/elements-nix --arg withCoverage true` on your default nixpkgs?  I've tried but the feature tests always fail for me due to timeouts.  I'm not sure if it is just my slow system or something actually broken.

**Comment by apoelstra** [comment]
Yep, this works for me!

**Comment by roconnor-blockstream** [comment]
A referece to a recent draft PR to Bitcoin Core's to enable clangs native coverage toolchain: https://github.com/bitcoin/bitcoin/pull/31394

**Pull request merged**
